### ISSUE TITLE
Is this even implemented?

### ISSUE THREAD

**Issue by crazyfx1** [mattleibow/RestSharp.Portable#1]

**Comment by icnocop** [comment]
https://github.com/FubarDevelopment/restsharp.portable

**Comment by mattleibow** [comment]
If you don't need PCL, you could try the official repo that is .NET Standard 2.0: https://github.com/restsharp/RestSharp

**Comment by crazyfx1** [comment]
Thanks for the info, But 2 years ago, when I opened the issue, .NET Core 1.0 was not even released yet ;)
